use_frameworks!
platform :ios, '10.0'

project 'SmartReplyExample.xcodeproj'

# [START smartreply_pod]
pod 'GoogleMLKit/SmartReply'
# [END smartreply_pod]

pod 'MaterialComponents/Buttons'
pod 'MaterialComponents/Chips'
pod 'MaterialComponents/List'
pod 'MaterialComponents/TextFields'
pod 'MaterialComponents/Buttons+ButtonThemer'
pod 'SwiftLint'

target 'SmartReplyExample' do
end
target 'SmartReplyExampleSwift' do
end
