use_frameworks!
platform :ios, '12.0'

project 'SmartReplyExample.xcodeproj'

pod 'GoogleMLKit/SmartReply', '2.5.0'

pod 'MaterialComponents'
pod 'SwiftLint'

target 'SmartReplyExampleObjC' do
end
target 'SmartReplyExample' do
end
