platform :ios, '10.0'
use_frameworks!

project 'AutoMLExample.xcodeproj'

pod 'GoogleMLKit/Common', '3.1.0'
pod 'GoogleMLKit/ImageLabelingCustom', '3.1.0'
pod 'GoogleMLKit/LinkFirebase', '3.1.0'
pod 'GoogleMLKit/ObjectDetectionCustom', '3.1.0'
pod 'GoogleMLKit/Vision', '3.1.0'

target 'AutoMLExample' do
end

target 'AutoMLExampleObjc' do
end
