use_frameworks!

platform :ios, '10.0'

project 'TranslateExample.xcodeproj'

pod 'GoogleMLKit/Translate', '2.5.0'

target 'TranslateExample' do
  target 'TranslateExampleTests' do
    inherit! :search_paths
  end
end

target 'TranslateExampleObjC' do
  target 'TranslateExampleObjCTests' do
    inherit! :search_paths
  end
end

target 'TranslateExampleUITests' do
end
