# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'sso://cpdc-test/mlkit'
source 'https://github.com/CocoaPods/Specs.git'

target 'objc-snippets' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for objc-snippets
  pod 'MLKitCommon'
  pod 'MLKitImageClassificationAutoML'
  pod 'MLKitVision'
end

target 'swift-snippets' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for swift-snippets
  pod 'MLKitCommon'
  pod 'MLKitImageClassificationAutoML'
  pod 'MLKitVision'
end
