platform :ios, '10.0'
use_frameworks!

project 'VisionExample.xcodeproj'

pod 'GoogleMLKit/BarcodeScanning', '2.4.0'
pod 'GoogleMLKit/FaceDetection', '2.4.0'
pod 'GoogleMLKit/ImageLabeling', '2.4.0'
pod 'GoogleMLKit/ImageLabelingCustom', '2.4.0'
pod 'GoogleMLKit/ObjectDetection', '2.4.0'
pod 'GoogleMLKit/ObjectDetectionCustom', '2.4.0'
pod 'GoogleMLKit/PoseDetection', '2.4.0'
pod 'GoogleMLKit/PoseDetectionAccurate', '2.4.0'
pod 'GoogleMLKit/SegmentationSelfie', '2.4.0'
pod 'GoogleMLKit/TextRecognition', '2.4.0'
pod 'GoogleMLKit/TextRecognitionChinese', '2.4.0'
pod 'GoogleMLKit/TextRecognitionDevanagari', '2.4.0'
pod 'GoogleMLKit/TextRecognitionJapanese', '2.4.0'
pod 'GoogleMLKit/TextRecognitionKorean', '2.4.0'

target 'VisionExample' do
end

target 'VisionExampleObjC' do
end
