platform :ios, '10.0'
use_frameworks!

project 'VisionExample.xcodeproj'

pod 'GoogleMLKit/BarcodeScanning', '3.0.0'
pod 'GoogleMLKit/FaceDetection', '3.0.0'
pod 'GoogleMLKit/ImageLabeling', '3.0.0'
pod 'GoogleMLKit/ImageLabelingCustom', '3.0.0'
pod 'GoogleMLKit/ObjectDetection', '3.0.0'
pod 'GoogleMLKit/ObjectDetectionCustom', '3.0.0'
pod 'GoogleMLKit/PoseDetection', '3.0.0'
pod 'GoogleMLKit/PoseDetectionAccurate', '3.0.0'
pod 'GoogleMLKit/SegmentationSelfie', '3.0.0'
pod 'GoogleMLKit/TextRecognition', '3.0.0'
pod 'GoogleMLKit/TextRecognitionChinese', '3.0.0'
pod 'GoogleMLKit/TextRecognitionDevanagari', '3.0.0'
pod 'GoogleMLKit/TextRecognitionJapanese', '3.0.0'
pod 'GoogleMLKit/TextRecognitionKorean', '3.0.0'

target 'VisionExample' do
end

target 'VisionExampleObjC' do
end
