use_frameworks!
platform :ios, '11.0'

project 'LanguageIDExample.xcodeproj'

pod 'GoogleMLKit/LanguageID', '4.0.0'

target 'LanguageIDExample' do
end

target 'LanguageIDExampleObjC' do
end

# Disable signing for pods
post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
         end
    end
  end
end