source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'
# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!

pod 'GoogleMLKit/ObjectDetection'
pod 'GoogleMLKit/ObjectDetectionCustom'

pod 'MaterialComponents'
pod 'PINRemoteImage'

target 'ShowcaseApp' do
end
