platform :ios, '10.0'
use_frameworks!

project 'EntityExtractionExample.xcodeproj'

pod 'GoogleMLKit/EntityExtraction', '2.5.0'

target 'EntityExtractionExample' do
end

target 'EntityExtractionExampleObjC' do
end
